---
name: Foundry CI


permissions: {}


on:
  push:
  pull_request:
  workflow_dispatch:


env:
  FOUNDRY_PROFILE: ci


jobs:
  erc20:
    name: Build ERC20 demo project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      wd: ./01-erc20
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Show Forge version
        run: forge --version
      - name: Run Forge fmt
        working-directory: ${{ env.wd }}
        run: forge fmt --check
      - name: Run Forge build
        working-directory: ${{ env.wd }}
        run: forge build --sizes
